### ISSUE TITLE
Set up Main Look (GUI)

### ISSUE THREAD

**Issue by kathrync23** [AugustanaCSC490Spring2020/AugieAthleticsApp#1]
Set up how the app is supposed to look like so that we can get the backend stuff set up.

**Comment by brysonadcock** [comment]
Basic Activities made.  Styling and buttons need to be implements to jump from each activity

**Comment by brysonadcock** [comment]
Structure of the GUI is primarily in place but will need to be tweaked with the data implementation

**Comment by brysonadcock** [comment]
Small tweaks left but GUI is primarily ready
