### ISSUE TITLE
Login exception

### ISSUE THREAD

**Issue by faisalnawaz16** [AugustanaCSC490Spring2020/AugieAthleticsApp#14]

**Comment by kathrync23** [comment]
What specifically is this referring to?

**Comment by faisalnawaz16** [comment]
exception when logging in using gmail

**Comment by kathrync23** [comment]
Are you still having this problem? You're the only one so far to have problems when logging in. Maybe you need to add your SHA-1 key to firebase? Here's a tutorial on how to do that: https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application

**Comment by brysonadcock** [comment]
Works
