### ISSUE TITLE
Learn how to do Push Notifications 

### ISSUE THREAD

**Issue by kathrync23** [AugustanaCSC490Spring2020/AugieAthleticsApp#3]
This will be the first step in implementing the push notifications into our app. 
Just learn how to do it in a way to be able to quickly explain it to the others.

**Comment by brysonadcock** [comment]
Figured out what code I need but still need to figure out where the code should go in the project and how to implement

**Comment by brysonadcock** [comment]
Implemented without Firebase so I'm not entirely sure if it works or not and I'm not sure how to tell since there aren't any games until September
