### ISSUE TITLE
Calendar Integration

### ISSUE THREAD

**Issue by kathrync23** [AugustanaCSC490Spring2020/AugieAthleticsApp#4]
Learn how to do calendar integration. 
This is the first step in implementing calendar integration. The calendar integration is when we are adding events from our app into the person's calendar. 

DIFFERENT FROM HAVING A CALENDAR WITHIN THE APP. See other calendar issue

**Comment by JennaEMorgan** [comment]
Tutorial: https://code.tutsplus.com/tutorials/android-essentials-adding-events-to-the-users-calendar--mobile-8363

**Comment by kathrync23** [comment]
maybe use a webview for the calendar within the app instead?

**Comment by kathrync23** [comment]
Ended up not doing this
