### ISSUE TITLE
Google Sign in set up

### ISSUE THREAD

**Issue by kathrync23** [AugustanaCSC490Spring2020/AugieAthleticsApp#8]
Set up the Google sign in so they can keep their favorites across multiple devices.

**Comment by brysonadcock** [comment]
Let's figure out why its not popping up, add sign-in button

**Comment by brysonadcock** [comment]
Login Feature is there but is not connected to firebase authentication yet

**Comment by brysonadcock** [comment]
Authentication works, but need to figure out how to access user information in the app now
